# Generated by Django 5.0.7 on 2024-08-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_accueil_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vague_name', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField()),
            ],
        ),
    ]
