# Generated by Django 5.0.7 on 2024-08-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_event_date_countdown_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=models.ImageField(upload_to='media/about/'),
        ),
        migrations.AlterField(
            model_name='accueil',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='accueil',
            name='logo',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='image1',
            field=models.ImageField(upload_to='media/evalutation/'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='image2',
            field=models.ImageField(upload_to='media/evalutation/'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='image3',
            field=models.ImageField(upload_to='media/evalutation/'),
        ),
    ]
